/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/UI/Alert/Alert.vue')['default']
    AsideExercise: typeof import('./src/components/AsideExercise/AsideExercise.vue')['default']
    Avatar: typeof import('./src/components/UI/Avatar/Avatar.vue')['default']
    BodySvg: typeof import('./src/components/BodySvg/BodySvg.vue')['default']
    Button: typeof import('./src/components/UI/Button/Button.vue')['default']
    ButtonClose: typeof import('./src/components/UI/ButtonClose/ButtonClose.vue')['default']
    Calendar: typeof import('./src/components/Calendar/Calendar.vue')['default']
    Checkbox: typeof import('./src/components/UI/Checkbox/Checkbox.vue')['default']
    ChosenExerciseSets: typeof import('./src/components/ChosenExercisesList/ChosenExerciseSets/ChosenExerciseSets.vue')['default']
    ChosenExercisesList: typeof import('./src/components/ChosenExercisesList/ChosenExercisesList.vue')['default']
    ColorTheme: typeof import('./src/components/ColorTheme/ColorTheme.vue')['default']
    Dropdown: typeof import('./src/components/UI/Dropdown/Dropdown.vue')['default']
    DropdownColor: typeof import('./src/components/UI/DropdownColor/DropdownColor.vue')['default']
    EventsFuncsDropdown: typeof import('./src/components/ExercisesList/EventsFuncsDropdown/EventsFuncsDropdown.vue')['default']
    EventsList: typeof import('./src/components/EventsList/EventsList.vue')['default']
    EventsMode: typeof import('./src/components/EventsMode/EventsMode.vue')['default']
    Exercises: typeof import('./src/components/ExercisesList/Exercises/Exercises.vue')['default']
    ExercisesList: typeof import('./src/components/ExercisesList/ExercisesList.vue')['default']
    GroupInputs: typeof import('./src/components/UI/GroupInputs/GroupInputs.vue')['default']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    Icon: typeof import('./src/components/UI/Icon/Icon.vue')['default']
    Input: typeof import('./src/components/UI/Input/Input.vue')['default']
    Loading: typeof import('./src/components/UI/Loading/Loading.vue')['default']
    Modal: typeof import('./src/components/UI/Modal/Modal.vue')['default']
    MuscleItemHeader: typeof import('./src/components/ExercisesList/MuscleItemHeader/MuscleItemHeader.vue')['default']
    MySelect: typeof import('./src/components/UI/MySelect/MySelect.vue')['default']
    Popup: typeof import('./src/components/UI/Popup/Popup.vue')['default']
    Program: typeof import('./src/components/Program/Program.vue')['default']
    Radio: typeof import('./src/components/UI/Radio/Radio.vue')['default']
    ReadModal: typeof import('./src/components/ReadModal/ReadModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchExercises: typeof import('./src/components/SearchExercises/SearchExercises.vue')['default']
    SetExerciseForm: typeof import('./src/components/ChosenExercisesList/SetExerciseForm/SetExerciseForm.vue')['default']
    Tabs: typeof import('./src/components/UI/Tabs/Tabs.vue')['default']
    Tooltip: typeof import('./src/components/UI/Tooltip/Tooltip.vue')['default']
    TransitionSlideY: typeof import('./src/components/UI/Transitions/TransitionSlideY.vue')['default']
    UserForm: typeof import('./src/components/Account/UserForm.vue')['default']
    WorkoutDescription: typeof import('./src/components/Workout/WorkoutDescription.vue')['default']
  }
}
